### PR TITLE
QxR regex modified to stop matching a Taoe release

### PR DESCRIPTION
**Pull request by wheat4714**
`Futurama (1999) S06E18 The Silence of the Clamps (1080p BDRip x265 10bit AC3 5.1 - Goki)[TAoE]`
`Futurama (1999) S06E16 Ghost in the Machines (1080p BDRip x265 10bit AC3 5.1 - Goki)[TAoE]`
`Foundation (2021) S01E03 The Mathematician’s Ghost (1080p ATVP Webrip x265 10bit EAC3 5 1 Atmos - Goki)[TAoE]`

Preventing matches for the above. "Silence" and "Ghost" are common words, so we might want to think about a better way to handle this, such as an x265 verified encoder list, which we can use as a negate, or some way of matching silence and ghost but not match episode names.

### CODE REVIEW

**Comment by wheat4714** [comment]
Regex has been improved. 

Matches:
Stranger Things 2016 Season 2 S02 1080p BluRay x265 HEVC 10bit AAC 5.1 - Silence
Superstore (2015) S06 (1080p AMZN WEB-DL x265 SDR DDP 5.1 English - Silence QxR)
Sharp Objects (2018) S01 (1080p BluRay x265 SDR AAC 5.1 English - Silence QxR)
21 Up (1977) 1080p BluRay x265 SDR AAC 2.0 English -Silence

Does not match:
Futurama (1999) S06E18 The Silence of the Clamps (1080p BDRip x265 10bit AC3 5.1 - Goki)[TAoE]
The.Silence.of.the.Lambs.1991.2160p.UHD.BluRay.DTS-HD.MA.5.1.DV.x265-W4NK3R
Blast of Silence (1961) 1080p CRIT WEB-DL H264 SDR AAC 1.0 English-KUCHU

**Comment by wheat4714** [comment]
`Rick.and.Morty.S04E09.Childrick.of.Mort.Uncensored.1080p.WEB-DL.DD5.1.x265.10bit-TimeDistortion`

no longer matching

**Comment by santiagosayshey** [comment]
@wheat4714 Would you be able to ask Yogi what theft is?

[Crazy.Ex-Girlfriend.2015-S01E01-Josh.Just.Happens.to.Live.Here.1080p.AMZN.WEB-DL.x265.RZeroX[Theft]](https://nzbgeek.info/geekseek.php?guid=4b34be7024df0bc4468d769d0bb0e40e)

**Review by santiagosayshey — CHANGES_REQUESTED** [review]
Good work on this one.

Still some edge cases to fix, mostly to do with `.`'s before group names. Also 1 UTR fail.

See the tests for more details.

**Comment by wheat4714** [comment]
Why does QxR need to NOT match this?
`Achile-Kappa-(G0100042797863)-SINGLE-16BIT-WEB-FLAC-2020-PacificatedLittleness`

As it's audio, sonarr wouldn't check it anyway? It's the wrong category.

**Comment by wheat4714** [comment]
UTR regex improved: https://regex101.com/r/IR6foP/1

The ONLY failure is a music release, but I don't see how that's relevant if it's not in the TV category.

**Review by santiagosayshey — APPROVED** [review]
Approved!

**Pull request merged**
